name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3


      - name: 🔧 Install java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'

      - name: 🔧 Install clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.943'

      - name: 🗝 maven cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 🗝 Clerk Cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-clerk

      - name: 🏗 Clerk Build
        run: clojure -X:nextjournal/clerk :path-prefix '"jointprob-clerk/"' :git/sha '"${{ github.sha }}"'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: public/build # The folder the action should deploy.
